[project]
name = "qbt-shaper"
version = "0.0.1"
description = ""
authors = []
readme = "README.md"
requires-python = ">=3.12.0,<4"
dependencies = [
    "aiohttp>=3.13.5",
    "homeassistant-api>=6.0.0",
    "pydantic>=2.13.3",
    "pydantic-settings>=2.14.0",
    "python-dotenv>=1.2.2",
    "qbittorrent-api>=2026.5.0",
]

[project.optional-dependencies]
type = ["mypy>=1.19.0", "ty>=0.0.23"]

lint = ["ruff>=0.15.6"]

test = [
    "pytest>=9.0.0",
    "coverage>=7.13.0",
    "pytest-mock",
    "pytest-random-order",
    "detect-test-pollution",
]

[project.urls]
Repository = "https://github.com/kism/python-boilerplate"

[build-system]
requires = ["uv_build>=0.11.0,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[project.scripts]
qbt-shaper = "qbt_shaper:__main__.main"

[tool.ruff]
cache-dir = "~/.cache/ruff"
target-version = "py312"
line-length = 120

[tool.ruff.lint]
select = ["ALL"] # Include absolutely all of Ruff's rules.
ignore = [
    # Modules
    "DJ",   # Django not required
    "AIR",  # Airflow not required
    "FAST", # FastAPI not required
    "DTZ",  # no need to specify timezone for time objects

    # Specific rules
    "TD002",  # Verbose TODO, only I work on this project
    "TD003",  # Verbose TODO, only I work on this project
    "ISC001", # conflict in the formatter
    "COM812", # conflict in the formatter
    "D",      # Don't care about docstrings
    "G201",   # Happy to log exceptions as errors
    "TRY400", # Fine to log web exceptions as errors
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = [
    # Modules
    "ARG", # Unused function args -> fixtures nevertheless are functionally relevant
    "FBT", # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    "ANN", # Don't care about annotations in tests
    "D",   # Don't care about docstrings in tests

    # Specific rules
    "S101",    # asserts allowed in tests.
    "SLF001",  # Accessing private members is needed for testing.
    "INP001",  # __init__.py not needed for PyTest.
    "PT004",   # monkeypatch doesn't return.
    "S311",    # I'll assume no real crypto will be done in PyTest.
    "S105",    # Hardcoded fake passwords are fine in tests.
    "PLR0913", # Tests can have as many arguments as they want.
    "BLE001",  # Tests can use BaseException.
    "S311",    # Regular RNG is fine in tests.
]


[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 40

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
command_line = ".venv/bin/pytest"
source = ["qbt_shaper"]
context = "test"

[tool.coverage.report]
show_missing = false
format = "text"
sort = "-Miss"

[tool.coverage.html]
show_contexts = true

[tool.mypy]
files = ["qbt_shaper", "tests"]
show_error_codes = true
strict = true
enable_error_code = [
    "ignore-without-code",
    "redundant-expr",
    "truthy-bool",
    "type-arg",
    "unused-awaitable",
    "possibly-undefined",
    "redundant-self",
]
warn_unreachable = true
warn_redundant_casts = true
warn_no_return = true
